language: node_js
node_js:
  - 16

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: true
        on:
          branch: master
        script: npx semantic-release